// TODO Load this from chains

export const extraData = {
  Solana: {
    delegators: 41,
    totalStake: 292791,
    commission: 7,
    website: 'https://solana.com/',
    websiteFriendly: 'solana.com',
    marketcap: 270018859,
  },
  Kusama: {
    delegators: 4,
    totalStake: 6314,
    commission: 10,
    website: 'https://kusama.network/',
    websiteFriendly: 'kusama.network',
    marketcap: 8470098,
  },
  Polkadot: {
    delegators: 14,
    totalStake: 6200,
    commission: 0,
    website: 'https://polkadot.network/',
    websiteFriendly: 'polkadot.network',
    marketcap: 929768387,
  },
  Mina: {
    delegators: 1,
    totalStake: 66000,
    commission: 5,
    website: 'https://minaprotocol.com/',
    websiteFriendly: 'minaprotocol.com',
  },
  Centrifuge: {
    delegators: 4,
    totalStake: 3.2,
    commission: 2,
    website: 'https://centrifuge.io/',
    websiteFriendly: 'centrifuge.io',
  },
  Terra: {
    delegators: 1,
    totalStake: 143191,
    commission: 5,
    website: 'https://terra.money/',
    websiteFriendly: 'terra.money',
    marketcap: 377828959,
  },
  Regen: {
    delegators: 15,
    totalStake: 976896,
    commission: 2,
    stakeLink: 'https://wallet.keplr.app/#/regen/stake',
    website: 'https://www.regen.network/',
    websiteFriendly: 'regen.network',
    marketcap: 100000000,
  },
  'Fetch.AI': {
    delegators: 4,
    totalStake: 322609,
    commission: 2,
    stakeLink: 'https://staking.fetch.ai/#/',
    website: 'https://fetch.ai/',
    websiteFriendly: 'fetch.ai',
    marketcap: 746113681,
  },
  Sora: {
    delegators: 25,
    totalStake: 185,
    commission: 5,
    stakeLink:
      'https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.sora2.soramitsu.co.jp#/staking/actions',
    website: 'https://sora.org/',
    websiteFriendly: 'sora.org',
    marketcap: 350000,
  },
  Osmosis: {
    delegators: 25,
    totalStake: 6022,
    commission: 5,
    stakeLink: 'https://wallet.keplr.app/#/osmosis/stake',
    website: 'https://app.osmosis.zone/',
    websiteFriendly: 'app.osmosis.zone',
    marketcap: 325000000,
  },
};
