// TODO Load this from chains

export const extraData = {
  Solana: {
    delegators: 731,
    totalStake: 502833,
    commission: 10,
    website: 'https://solana.com/',
    websiteFriendly: 'solana.com',
    marketcap: 320489450,
  },
  Kusama: {
    delegators: 12,
    totalStake: 6314,
    commission: 15,
    website: 'https://kusama.network/',
    websiteFriendly: 'kusama.network',
    marketcap: 8470098,
  },
  Mina: {
    delegators: 1,
    totalStake: 66000,
    commission: 5,
    website: 'https://minaprotocol.com/',
    websiteFriendly: 'minaprotocol.com',
  },
  Centrifuge: {
    delegators: 4,
    totalStake: 3.2,
    commission: 2,
    website: 'https://centrifuge.io/',
    websiteFriendly: 'centrifuge.io',
  },
  Regen: {
    delegators: 15,
    totalStake: 976896,
    commission: 2,
    stakeLink:
      'https://wallet.keplr.app/#/regen/stake?modal=stake&chainId=regen-1&validator=regenvaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3uupmg2z',
    website: 'https://www.regen.network/',
    websiteFriendly: 'regen.network',
    marketcap: 100000000,
  },
  'Fetch.AI': {
    delegators: 12,
    totalStake: 322609,
    commission: 8,
    stakeLink: 'https://staking.fetch.ai/#/',
    website: 'https://fetch.ai/',
    websiteFriendly: 'fetch.ai',
    marketcap: 746113681,
  },
  Osmosis: {
    delegators: 102,
    totalStake: 253000,
    commission: 5,
    stakeLink:
      'https://wallet.keplr.app/#/osmosis/stake?modal=stake&chainId=osmosis-1&validator=osmovaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3udgkz9z',
    website: 'https://app.osmosis.zone/',
    websiteFriendly: 'app.osmosis.zone',
    marketcap: 325000000,
  },
  Velas: {
    delegators: 12,
    totalStake: 5163934,
    commission: 5,
    stakeLink: 'https://velasvalidators.com/covermNdkWB48b5m8VVYCvo9wovigsZMoBJRZtk5WqT',
    website: 'https://velas.com/',
    websiteFriendly: 'velas.com',
    marketcap: 2124380663,
  },
  Chihuahua: {
    delegators: 65,
    totalStake: 65722105,
    commission: 5,
    stakeLink: 'https://chihuahua.omniflix.co/stake',
    website: 'https://www.chihuahua.wtf/',
    websiteFriendly: 'chihuahua.wtf',
    marketcap: 103000000000,
  },
  Cerberus: {
    delegators: 12,
    totalStake: 22683643,
    commission: 5,
    stakeLink: 'https://stake.cerberus.zone/',
    website: 'https://cerberus.zone/',
    websiteFriendly: 'cerberus.zone',
    marketcap: 100000000000,
  },
  Concordium: {
    delegators: 2,
    totalStake: 1036000,
    commission: 0,
    website: 'https://www.concordium.com/',
    websiteFriendly: 'concordium.com',
    marketcap: 2124380663,
  },
  Evmos: {
    delegators: 127,
    totalStake: 357124,
    commission: 5,
    stakeLink:
      'https://wallet.keplr.app/#/evmos/stake?modal=stake&chainId=evmos_9001-2&validator=evmosvaloper1kualgrr9qup0983gj44fczyvcda8ea47y494mz',
    website: 'https://evmos.org/',
    websiteFriendly: 'evmos.org',
    marketcap: 0,
  },
  'Aleph Zero': {
    delegators: 7,
    totalStake: 127500,
    commission: 5,
    stakeLink: 'https://azero.dev/#/staking/actions',
    website: 'https://alephzero.org/',
    websiteFriendly: 'alephzero.org',
    marketcap: 0,
  },
  Rebus: {
    delegators: 147,
    totalStake: 521000,
    commission: 5,
    stakeLink: 'https://app.rebuschain.com/staking',
    website: 'https://www.rebuschain.com/',
    websiteFriendly: 'rebuschain.com',
    marketcap: 0,
  },
  Acrechain: {
    delegators: 7,
    totalStake: 468000,
    commission: 12,
    stakeLink: 'https://cosmosrun.info/acre-mainnet',
    website: 'https://arable.finance/',
    websiteFriendly: 'arable.finance',
    marketcap: 0,
  },
};
