import { INetwork } from '../redux/types';

export const networks: INetwork[] = [
  {
    name: 'Solana',
    address: 'cover89z945JotsCRGdbjakJm4rnL5XspFSPgN1mVZj',
    icon: 'solana-logo.svg',
    mainnet: true,
    live: true,
    id: 'solana',
    symbol: 'SOL',
    hasPrice: true,
    stakingRatio: '62.83',
  },
  {
    name: 'Osmosis',
    address: 'osmovaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3udgkz9z',
    icon: 'osmosis-logo.svg',
    mainnet: true,
    live: true,
    id: 'osmos',
    symbol: 'OSMO',
    hasPrice: false,
  },
  {
    name: 'Polkadot',
    address: '1KNoJGdAQ6KAur35cYQYHPnzMzhtAL6M3db59uanQJ1NPv4',
    icon: 'polkadot-logo.svg',
    mainnet: true,
    live: true,
    id: 'polkadot',
    symbol: 'DOT',
    hasPrice: true,
    stakingRatio: '65.09',
  },
  {
    name: 'Kusama',
    address: 'EkpjJUusZu4FZxzC1EyYxoyCxKVGKAd5aEygoF38tqSv3C3',
    icon: 'kusama-logo.svg',
    mainnet: true,
    live: true,
    id: 'kusama',
    symbol: 'KSM',
    hasPrice: true,
    stakingRatio: '49.81',
  },
  {
    name: 'Terra',
    address: 'terravaloper12ce886lv4muzt09rgehsta8433d8vz7cxmha0p',
    icon: 'terra-logo.svg',
    mainnet: true,
    live: true,
    id: 'terra',
    symbol: 'LUNA',
    hasPrice: true,
    stakingRatio: '33',
  },
  {
    name: 'Mina',
    address: 'B62qqTGc21K1mJo9adVuKwRddiUD5cQxocu2BxaahQGfrQzvWBc7UYv',
    icon: 'mina-logo.png',
    mainnet: true,
    live: true,
    id: 'mina',
    symbol: 'MINA',
    hasPrice: false,
  },
  {
    name: 'Regen',
    address: 'regenvaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3uupmg2z',
    icon: 'regen-logo.png',
    mainnet: true,
    live: true,
    id: 'regen',
    symbol: 'REGEN',
    hasPrice: false,
  },
  {
    name: 'Centrifuge',
    address: '4dXFX2tcwTdmZZikz79nPbrRBTBV8YaKVZ5Sc37Gsy42V2uU',
    icon: 'centrifuge-logo.svg',
    mainnet: true,
    live: true,
    id: 'centrifuge',
    symbol: 'RAD',
    hasPrice: false,
  },
  {
    name: 'Fetch.AI',
    address: 'fetchvaloper17w7shen7vd9ljl868hlqe2rphxlksu7vxurwdn',
    icon: 'fetch-logo.svg',
    mainnet: true,
    live: true,
    id: 'fetch',
    symbol: 'FET',
    hasPrice: true,
  },
  {
    name: 'Sora',
    address: 'cnTfngsED6ZqgaPo1b3exzoynteT8jxurDt5hJGu2zqcn9f5T',
    icon: 'sora-logo.svg',
    mainnet: true,
    live: true,
    id: 'sora',
    symbol: 'XOR',
    hasPrice: true,
  },
];
