import { INetwork } from '../redux/types';

export const networks: INetwork[] = [
  {
    name: 'Solana',
    address: 'cover89z945JotsCRGdbjakJm4rnL5XspFSPgN1mVZj',
    icon: 'solana-logo.svg',
    mainnet: true,
    live: true,
    id: 'solana',
    symbol: 'SOL',
    hasPrice: true,
    description:
      'Solana is a high-performance blockchain known for its incredibly fast transaction speeds and low fees. It leverages a unique hybrid consensus model combining Proof of History (PoH) with Proof of Stake (PoS) to offer efficient and scalable decentralized solutions, making it a popular choice for developers and users in the DeFi, NFT, and decentralized app (dApp) spaces.',
  },
  {
    name: 'Aleph Zero',
    address: '5EFD4z93FCt8Vv9YRJRvf1Sy4N3FTeMSdCQEJ8y5f6cxB5Pw',
    icon: 'azero.png',
    mainnet: true,
    live: true,
    id: 'azero',
    symbol: 'AZERO',
    hasPrice: true,
  },
  {
    name: 'Osmosis',
    address: 'osmovaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3udgkz9z',
    icon: 'osmosis-logo.svg',
    mainnet: true,
    live: true,
    id: 'osmos',
    symbol: 'OSMO',
    hasPrice: true,
  },
  {
    name: 'Mina',
    address: 'B62qqTGc21K1mJo9adVuKwRddiUD5cQxocu2BxaahQGfrQzvWBc7UYv',
    icon: 'mina-logo.png',
    mainnet: true,
    live: true,
    id: 'mina',
    symbol: 'MINA',
    hasPrice: false,
  },
  {
    name: 'Kusama',
    address: 'EkpjJUusZu4FZxzC1EyYxoyCxKVGKAd5aEygoF38tqSv3C3',
    icon: 'kusama-logo.svg',
    mainnet: true,
    live: true,
    id: 'kusama',
    symbol: 'KSM',
    hasPrice: true,
  },
  {
    name: 'Fetch.AI',
    address: 'fetchvaloper17w7shen7vd9ljl868hlqe2rphxlksu7vxurwdn',
    icon: 'fetch-logo.svg',
    mainnet: true,
    live: true,
    id: 'fetch',
    symbol: 'FET',
    hasPrice: true,
  },
  {
    name: 'Concordium',
    address: 'ee62e159d921835c',
    icon: 'concordium.png',
    mainnet: true,
    live: true,
    id: 'concordium',
    symbol: 'CCD',
    hasPrice: true,
  },
  {
    name: 'Evmos',
    address: 'evmosvaloper1kualgrr9qup0983gj44fczyvcda8ea47y494mz',
    icon: 'evmos.svg',
    mainnet: true,
    live: true,
    id: 'evmos',
    symbol: 'EVMOS',
    hasPrice: false,
  },
  {
    name: 'Chihuahua',
    address: 'chihuahuavaloper15mennjck93a5v990hrngf3hxskjx6vztx6a7y0',
    icon: 'chihuahua.svg',
    mainnet: true,
    live: true,
    id: 'chihuahua',
    symbol: 'HUAHUA',
    hasPrice: true,
  },
  // {
  //   name: 'Cerberus',
  //   address: 'cerberusvaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3ukj8ltz',
  //   icon: 'crbrus.png',
  //   mainnet: true,
  //   live: true,
  //   id: 'cerberus',
  //   symbol: 'CRBRUS',
  //   hasPrice: false,
  // },
  // {
  //   name: 'Velas',
  //   address: 'covermNdkWB48b5m8VVYCvo9wovigsZMoBJRZtk5WqT',
  //   icon: 'velas.svg',
  //   mainnet: true,
  //   live: true,
  //   id: 'velas',
  //   symbol: 'VLX',
  //   hasPrice: true,
  //   stakingRatio: '5',
  // },
  // {
  //   name: 'Regen',
  //   address: 'regenvaloper1273zsxhxd5dlgcr2zjf5x25275hjcp3uupmg2z',
  //   icon: 'regen-logo.png',
  //   mainnet: true,
  //   live: true,
  //   id: 'regen',
  //   symbol: 'REGEN',
  //   hasPrice: true,
  // },
  // {
  //   name: 'Centrifuge',
  //   address: '4dXFX2tcwTdmZZikz79nPbrRBTBV8YaKVZ5Sc37Gsy42V2uU',
  //   icon: 'centrifuge-logo.svg',
  //   mainnet: true,
  //   live: true,
  //   id: 'centrifuge',
  //   symbol: 'CFG',
  //   hasPrice: true,
  // },
  // {
  //   name: 'Rebus',
  //   address: 'rebusvaloper1kualgrr9qup0983gj44fczyvcda8ea47y8yppz',
  //   icon: 'rebus.svg',
  //   mainnet: true,
  //   live: true,
  //   id: 'rebus',
  //   symbol: 'REBUS',
  //   hasPrice: true,
  // },
  // {
  //   name: 'Acrechain',
  //   address: 'acrevaloper1yzg7yh4yfju8dvc9wwls7dyvaqnzj2er5sluru',
  //   icon: 'arable.png',
  //   mainnet: true,
  //   live: true,
  //   id: 'acre',
  //   symbol: 'ACRE',
  //   hasPrice: true,
  // },
];
