name: CD Staging

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: CD Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Create .npmrc file
        run: |
          touch .npmrc
          echo //npm.greensock.com/:_authToken=${{ secrets.GSAP_TOKEN }} >> .npmrc
          echo @gsap:registry=https://npm.greensock.com >> .npmrc
            
      - name: Install dependencies
        run: npm i
        
      # - name: Lint
      #   run: npm run lint

      # - name: Typescript check
      #   run: npx tsc --noEmit   

      # - name: Run Unit Tests
      #   run: npm test   

      - name: Build
        run: npm run build
      
      - name: Deploy to staging server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Restart PM2 server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: CC_TOKEN=${{ secrets.CC_TOKEN }} pm2 restart 0  --update-env  
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }} 

      # - name: Upload coverage to codecov
      #   run: bash <(curl -s https://codecov.io/bash)